service: serverless-twitch-to-discord-webhooks

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  twitchOnline:
    handler: handler.online
    events:
      - httpApi:
          method: POST
          path: /v1/online
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:us-east-1:*:parameter/${sls:stage}/twitch/webhook/secret
          - arn:aws:ssm:us-east-1:*:parameter/${sls:stage}/discord/callback

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
