service: serverless-twitch-to-discord-webhooks

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  tags:
    application: Twitch Events

functions:
  twitchOnline:
    handler: twitch_callback.online
    events:
      - httpApi:
          method: POST
          path: /v1/online
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:us-east-1:*:parameter/${sls:stage}/twitch/webhook/secret
      - Effect: Allow
        Action:
          - events:PutEvents
        Resource:
          - !GetAtt twitchEventBus.Arn

  streamOnline:
    handler: stream_online.main
    environment:
      DISCORD_CALLBACKS_TABLE: !Ref discordCallbacks
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:us-east-1:*:parameter/${sls:stage}/discord/callback
          - arn:aws:ssm:us-east-1:*:parameter/${sls:stage}/twitch/*
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource:
          - !GetAtt discordCallbacks.Arn

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

resources:
  Resources:
    twitchEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: serverless-twitch-to-discord-webhooks-${sls:stage}

    twitchDiscoverer:
      Type: AWS::EventSchemas::Discoverer
      Properties:
        Description: Discovers twitch event bus events
        SourceArn: !GetAtt twitchEventBus.Arn

    onlineEventRule:
      Type: AWS::Events::Rule
      Properties:
        Description: Forwards twitch events to event_handler lambda
        EventBusName: !Ref twitchEventBus
        EventPattern:
          source:
            - stream.online
        State: ENABLED
        Targets:
          - Arn: !GetAtt StreamOnlineLambdaFunction.Arn
            Id: Twitch

    InvokeEventHandlerLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:invokeFunction
        FunctionName: !Ref StreamOnlineLambdaFunction
        Principal: events.amazonaws.com
        SourceArn: !GetAtt onlineEventRule.Arn

    discordCallbacks:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
